export enum EventEnum {

    ON_GAME_HIDE,
    ON_GAME_SHOW,
    START_CHANGE_SCENE_WITH_TRANSITION,
    START_LOAD_SCENE,
    ON_SCENE_LOAD_COMPLETE,
    EVENT_AFTER_SCENE_LAUNCH,
    TRANSITION_END,
    TRANSITION_START,
    TRANSITION_MID,
    TRANSITION_SHOW_HALF,
    TRANSITION_HIDE_HALF,
    TIME_SPEED,
    CHANGE_VERSION_NAME,
    RELEASE_RES_NOW,
    ON_ESC_TOUCH,
    ON_GAME_START,
    HIDE_MAGIC_SKILL,
    CLIENT_CONFIG_LOADED,
    COMBOX_SHOW,
    COMBOX_SELECT,
    ON_QUERY_RET,
    //login
    LOGOUT,
    LOGINNING_TIP,
    RECONNECT_SUC,
    RELOGIN_SUC,
    RELOGIN_FAIL,
    ENTER_GAME_SUC,
    FIRST_CREATE_ROLE,
    PING,
    REGEDIT_SUC,
    VERIFICATION_SEND_RESULT,
    MODULE_INIT,
    LOGIN_WX_ERROR,

    CONFIRM_PRIVACY_AGREEMENT,
    CREATE_LOGIN_BTN,
    /////////////////////socket
    SOCKET_ON_ERROR,
    SOCKET_ON_READY,
    SOCKET_CONNECTED,
    SOCKET_IDLE,
    ON_SOCKET_DATA,
    EXIT_GAME,
    RECONNECT_FAIL,

    /////////////////////loading
    REFRESH_LOADING_TIPS,
    UPDATE_COMPLETE,
    UPDATE_FAIL,
    UPDATE_PROGRESS,
    UPDATE_PROGRESS_HOT_UPDATE,
    START_HOT_UPDATE,
    END_HOT_UPDATE,
    NEED_DOWN_LOAD_NEW_APP,
    NOT_DOWN_LOAD_NEW_APP,


    ////////////////////////////////////// ui
    LIST_STOP_MOVE,
    TIPSREWARD_MALLFIRST,
    TIPSREWARD_REFRESH,
    SYSTEM_TIPS_SHOW,
    SYSTEM_TIPS_HIDE,
    HORN_TIPS_SHOW_END,
    TOP_TIPS_END,
    CLEAR_TOP_TIPS,
    CHANGE_LANG,
    CERTIFICATION_SUCCESS,
    ON_UNDERAGE_TIPS,
    TUJIAN_PRE_PAGE,
    TUJIAN_NEXT_PAGE,
    TUJIAN_REFRESH_PRENEXT_STATE,
    ADDICTION_VIEW_SHOED,
    ALL_CURR_MONSTER_LOCK,//当前图鉴页的怪物都未解锁
    // REDPACKET_VIEW_HIDE,
    SET_GUIDE_NODE,
    ENABLE_SHOW_SCIENCE_VIEW,
    REFRESH_POWER,
    ON_DIALOG_HIDE,//UI面板隐藏
    BOOK_EFFECT_PLAY_END,
    SHOW_START_BTN,
    QRCODE_IMG,
    SHARE_TASK_STATE,
    SHARE_AWARD_GET,
    SHARE_RECORD_GET,
    HEAD_PORTRAIT, //头像
    HEAD_PORTRAIT_FRAME, //头像框

    CP_TASK_VIEW_SHOWED,//显示关卡任务
    ON_TJ_EQUIP_CLICK,
    EQUIP_ITEM_DATA_END, //装备数据接收完成
    EQUIP_DATA, //个人装备数据
    EQUIP_ACTIVE, //装备激活
    EQUIP_UPGRADE, //装备升级
    FIRST_RECHARGE_END,
    FIRST_RECHARGE_PRIVATE,
    ON_FIRST_RECHARGE_RECIVED,
    REFRESH_MONTH_CARD,
    REFRESH_WEEK_CARD,
    AFTER_SHOW_DIALOG,
    REFRESH_CK_QUESTION,
    GROWGIFT_PRIVATE_REFRESH,
    REFRESH_BATTLE_PASS2,
    REFRESH_BATTLE_PASS3,
    REFRESH_BATTLE_PASS4,
    HIDE_MANHUA,

    NEW_SEVICE_RANKING_DATA,
    NEW_SEVICE_RANKING_CONFIG,
    ZERO_MALL_CONFIG,
    ZERO_MALL_DATA,
    ZERO_MALL_STATE_CHANGE,
    ACTIVE_TAQING_PAGE_CHANGE,
    ACTIVE_TAQING_CHOUKA_RET,
    ACTIVE_TAQING_CHOUKA_TASK_RET,
    ACTIVE_TAQING_LEI_CHONG_TASK_RET,
    ACTIVE_TAQING_DAILY_TASK_RET,
    ACTIVE_TAQING_SIGN,
    ACTIVE_TAQING_EXCHANGE_RET,
    ACTIVE_TAQING_MALL_RET,
    ACTIVE_TAQING_REFREST_EXCHANGE_GOODS_COUNT,
    ACTIVE_TAQING_CLOSE,
    ACTIVE_TAQING_INIT,
    ACTIVE_TAQING_SELECT_WISH_ITEM,
    ACTIVE_TAQING_SELECT_HECHENG_ITEM,
    ACTIVE_TAQING_HECHENG_SUCCESS,
    ACTIVE_TAQING_HECHENG_FAIL,
    ACTIVE_TAQING_HECHENG_REWARD,
    ADD_ROLL_TIPS,
    /////////////////////////////////////////sceneObject
    LOAD_COMPLETE,
    MAIN_BODY_ATTACHED,
    ON_SELF_REMOVE,
    ON_SO_REMOVE,
    ACTION_PLAY_END,
    LOOP_PLAY_END,
    LEVEL_CHANGE,
    ON_OBJ_DIE,
    ON_TOWER_LOADED,

    ON_NOTICE_INFO,
    ON_NULL_NOTICE_INFO,

    MONSTER_FROZEN,
    MONSTER_FLY,
    CHANGE_CD,

    ////////////////////////////////////// game logic
    ASTAR_DATA_CHANGE,
    GRID_STATE_CHANGE,
    INIT_MAP_COMPLETE,
    ON_MAP_TOUCH,
    ON_TOWER_TOUCH,
    ON_LUOBO_TOUCH,
    GAME_PAUSE,
    CREATE_MONSTER_STATE,
    KILL_MAP_ALL_MONSTER,
    CREATE_ALL_MONSTER_COMPLETE,

    MONSTER_CLEAR,
    MONSTER_RUN_AWARY,
    CREATE_BO_END,
    GAME_GOLD_CHANGE,
    ROBOT_COIN_CHANGE,
    MAP_LIFE_CHANGE,
    MAP_TIME_CHANGE,
    MAP_BO_CHANGE,
    MAP_BO_END,
    UNSELECT_TARFER,
    SELECT_TARFER,

    TOUCH_TOP_UI,

    ON_ENEMY_TOUCH,
    CREATURE_DIED,
    CREATURE_ON_HIT,
    DROP_GOLD,
    ADD_GOLD,
    FLOAT_DAMAGE,
    FLOAT_GOLD,
    FLOAT_SWITCH,
    CREATE_MONSTAR_READY,
    CREATE_BOSS,
    CREATE_MONSTER,
    HIDE_BOSS_BLOOD_BAR,
    ON_DAMAGE,
    EXCLUDE_BLOOD,
    ON_GROUP_BLOOD_CHANGE,
    REFRESH_BLOOD,
    KILL_ALL_SCENE_ITEN,
    INIT_MAP_DATA_END,
    HIDE_START_GAME,
    READY_SHOW_BOSS_DES,
    GROUP_HURT,
    GAME_SUCC,
    GAME_FAIL,
    INIT_CP_TASK,
    BEGIN_ITEM_CLICK,
    RELEASE_MAGIC_SKILL,
    /**完成某波 */
    COMPLETE_BO,
    CREATE_POS_STATE,

    LAST_WAR_ID_CHANGE,
    LAST_WAR_ID_CHANGE2,
    SHOW_TASK_TRACK_ITEM,
    SHOW_MU_BAN,
    HIDE_MU_BAN,
    SHOW_FAIL_GUIDE,
    //调试用
    DEBUG_SHOW_INFO,
    DEBUG_SHOW_HPINFO,
    ON_ENTER_WAR,//进入游戏场景
    DO_FAIL,//失败
    DO_REVIVE,//复活
    SELECT_BEGIN_BUFF,//开局buff
    FINISHLOSTFV,//开局buff
    OPEN_GUANTOU,
    BUFF_ITEM_MOVE_END,
    BEGIN_ADD_LOSE_ITEM,
    DO_EXIT_MAP,
    GOON_PLAY,
    ON_HURT,
    ON_ADD_HP,
    CAI_BAO_BOX_CREATE,
    CAT_SHOW_BUBBLE,
    CAT_HIDE_BUBBLE,
    CAT_SHOW_BUBBLE2,
    SHOW_MISSION_TIPS,
    CAT_HIDE_BUBBLE2,
    CLOSE_GUIDE_MISSION_TIPS,
    CAT_SHOW_FACE,
    CAT_HIDE_FACE,
    HIDE_LUOBO_BLOOD,
    STATUS_USERSKILL,
    //pvp
    SCROLL_MAP,
    SCROLL_MAP_END,
    LOCK_UPGRADE_TIP,
    ON_SO_TRANSFORM,
    DELETE_MAP_BLOOD,
    ADD_MAP_TIME,
    PVP_GUIDE_END,
    PVP_INVITE_STATE,

    /////////////////////////////////////////////////


    /////////////////////////////////////////////////////task
    /** 关卡任务状态改变*/
    CPTASK_STATE_CHANGE,
    /**数量改变 */
    CPTASK_COUNT_CHANGE,
    /**萝卜受伤了 */
    LUOBO_HURT,
    /** 卖塔*/
    SELL_TOWER,
    /**升级炮塔 */
    UPDATE_TOWER,

    UPDATE_TOWER_MAKE_UP,
    /**销毁场景物件生成的炮塔 */
    FIND_TOWER,
    /**任何原因移除的塔 */
    REMOVE_TOWER,
    TOWER_TO_DONOT_SELECT,
    SELECT_TOWER_SHOW,

    CREATE_TOWER_SHOW,
    PROGRESS,
    /**玩家主动建塔 */
    CREATE_TOWER,
    /**所有建塔（玩家主动+打场景物件生成的） */
    CREATE_TOWER_ALL,
    CREATE_TOWER_END,
    /**显示游戏开始倒计时 */
    SHOW_GAME_START_VIEW,
    /**退出场景 */
    EXIT_GAME_SCENE,
    EXIT_GAME_SCENE_END,
    DESTROY_DIALOG,
    ON_DIALOG_AFTER_HIDE,
    SHOW_DIALOG,
    HIDE_DIALOG,

    CP_GUIDE_TIPS_END,

    ///////////////////////////////////////////////////////item
    /**物品数量改变 */
    ITEM_COUNT_CHANGE,
    /**物品改变 */
    ITEM_CHANGE,
    /**体力改变 */
    TILI_CHANGE,
    //获得奖励
    GET_REWARD,
    //下发随机商品数据
    ON_RAND_LIST_GOODS,
    //附加卡
    GET_ADD_REWARD,
    ON_GETED_CARD,

    ///////////////////////////////////////////////////////towerStar
    REFRESH_PAGE,
    GET_CARD,
    UP_STAR_SUCC,
    ACTIVATE_TOWER,
    SHOW_MONSTER_INFO,
    FLY_CAT_TO_END,
    TOWER_DATA_INIT,
    UNLOCK_NEW_TOWER,
    FLY_EQUIP_END,
    TROOPS_TEMP_FIGHT_CHANGE,
    /************************************************ chapter ********************************/
    MAP_PAGEVIEW_FIRSTINIT,
    SELECT_CHAPTER,
    SCROLL_TO_POINT,
    REFRESH_CURR_POINT,
    UNLOCK_CHAPTER,
    ON_WORLD_WAR_LIST,
    ON_WORLD_WAR_DETAILS,
    MAP_PAGE_VIEW_SCROLL_END,
    MAP_PAGE_ITEM_SCROLL_TO_INDEX,
    MAP_PAGE_SELECT_INDEX,
    ON_MPA_PAGE_SELECT_INDEX,
    STRENGTH_NOTENOUGH,
    //////////////////////
    SCIENCE_UPGRADE,
    SCIENCE_RESET,
    SCIENCE_VIWE_EXIT,
    SCIENCE_TRY_CALC_RANGE_ATTACK_SPEED,
    SCIENCE_TRY_CALC_RANGE_ATTACK_HURT,
    SCIENCE_TRY_CALC_RANGE_ATTACK_DIST,
    SCIENCE_TRY_CALC_ATTACK_HURT,
    SCIENCE_TRY_CALC_ATTACK_HURT2,
    SCIENCE_TRY_CALC_BUFF,
    SCIENCE_SELECT_ITEM,


    TREATRUE_BG_OPACITY_TO_MAX,
    SHOW_LIGHT_CIRCLE,

    //shop
    CAN_PAY,

    //音乐
    MUSIC_STATE_CHANGE,
    TEST_BOUNTY_LABEL,

    //sign
    ON_SIN_CONFIG,
    ON_SIGN_PRIVATEINFO,
    CLOSE_DAYINFO_VIEW,
    SHOW_SIGN_TAB_VIEW,

    //guide
    CP_GUIDE_START,
    CP_GUIDE_END,
    CP_GUIDE_REFRESH_ARROW_POS,
    CP_GUIDE_CREATE_MONSTER,
    CP_GUIDE_HIDE_VIEW,
    CP_GUIDE_RELEASE_MAGIC_SKILL,

    SHOW_GUIDE_VIEW,
    HIDE_GUIDE_VIEW,
    SHOW_GUIDE_INFO_VIEW,
    HIDE_GUIDE_INFO_VIEW,
    SHOW_GUIDE_ARROW,
    ON_INIT_GUIDE,
    ON_SKIP,

    /****************************************  商城  ****************************************/
    MALL_LIST_GOODS_UPDATE,
    EXCHANGE_UP_PRIVATE_DATA,
    ON_MALL_PRIVATE_DATA,//用户商城购买的私有数据
    CHANGE_SHOP_TAP,
    /**************************************** java call js *********************************/
    JAVA_CALL_LOGIN_SUCCESS,
    JAVA_CALL_LOGIN_FAIL,
    JAVA_CALL_LOGIN_CANCEL,

    JAVA_CALL_SHARE_SUCCESS,
    JAVA_CALL_SHARE_FAIL,
    JAVA_CALL_SHARE_CANCEL,

    JAVA_CALL_PAY_SUCCESS,
    JAVA_CALL_PAY_FAIL,
    JAVA_CALL_PAY_CANCEL,
    JAVA_REEGIONALISM_RETURN,
    JAVA_CALL_SAVE_IMG_SUCCESS,
    JAVA_CALL_ON_GET_DEVICEID,

    JAVA_CALL_ON_ANTI_ADDICTION_SUCC,
    JAVA_CALL_ON_ANTI_ADDICTION_FAIL,
    JAVA_CALL_ON_ANTI_ADDICTION_CANCEL,

    JAVA_CALL_ON_LOGOUT_SUCC,
    JAVA_CALL_ON_LOGOUT_FAIL,

    JAVA_CALL_ON_EXIT_SUCC,
    JAVA_CALL_ON_EXIT_FAIL,

    JAVA_CALL_ON_REWARDAD_SUCC,
    JAVA_CALL_ON_REWARDAD_FAIL,
    JAVA_CALL_ON_REWARDAD_CLOSE,

    JAVA_CALL_ON_PERMISSION_SUCC,
    JAVA_CALL_ON_PERMISSION_FAIL,

    JAVA_CALL_ON_SDK_INIT_SUCC,
    JAVA_CALL_ON_SDK_INIT_FAIL,
    //debug
    DEBUG,

    //system guide
    SYSTEM_GUIDE_CLICK,
    SYSTEM_GUIDE_CLICK2,
    SYSTEM_GUIDE_REDUCTION_NODE,
    END_SYSTEM_GUIDE,
    END_SYSTEM_GUIDE2,
    SHOW_VIEW,
    SHOW_STAR_BOX,
    SHOW_SUCCESS_BTN,
    ENTER_MAP_SCENE,
    ENTER_HALL_SCENE,
    INIT_CHAPTER_END,
    SHOW_RPKG_BTN,
    CHECK_SYSTEM_OPEN_END,

    //皮肤
    FASHION_ACTIVE,
    FASHION_USE,
    FASHION_CANCEL,

    ////////////////////////////////////////////////////protomgr
    ON_EMAIL_RETURN,
    ON_EMAIL_TEXT_RETURN,
    ON_EMAIL_RECEIVE,

    /****************************************  图鉴消息  ****************************************/
    ON_MONSTER_UPDATE,//怪物图鉴私有数据更新
    NEW_MONSTER_CAN_GETREWARD,//新怪物图鉴可以领取奖励

    FEED_BACK_SUCC,
    ON_STRENTH_INIT,
    ON_STRENTH_PRIVATEDATA,//科技个人数据
    /////////////////////////////////////////////////////转盘
    ON_TURNTABLE_RET,//转盘结果返回
    TURNTABLE_EXCHANGE_SUCC,//实物兑换成功
    ON_TURNTABLE_REWARD,//转盘奖励返回


    ON_RELATION_DELETE,//删除好友确认
    ON_RELATION_RECOMMEND,//推荐好友
    ON_RELATION_UPDATE_NOTICE,//更新一条通知

    /****************************************  打折商城  ****************************************/
    ON_DISCOUNT_PRIVATE_DATA,//玩家私有数据
    ON_DISCOUNT_BUY_RET,//购买返回

    /////////////////////////////////////////////////猫咪公寓
    ENTER_HOUSE_FLOOR,
    BUY_FURNITURE_RET,
    SELECT_ROOM_ITEM,
    LOAD_HOUSE_COMPLETE,
    SELECT_FURNITUREITEM,
    MOVE_FURNITUREITEM,
    MOVE_CATROOM_BY_ITEM,
    REFRESH_FURNITUREITEM,
    CLEAR_FURNITUREITEM,
    SAVE_FURNITUREITEM,
    ON_SAVE_FURNITUREITEM_SUCCESS,
    // REFRESH_COMFORT,
    // UPDATE_LAST_REWARD_FLOOR,
    REFRESH_FRIEND_VISIT_PRIVATE,
    ON_GET_FRIEND_HOUSE_REWARD,
    ON_FRIEND_FURNITURE_INFO,
    ENTER_CAT_HOUSE_SCENE,
    ///////////////////////////////////////弹幕
    ON_WAR_BULLET_CHAT_RET,
    ON_WAR_MY_CHAT_RET,
    ON_BULLET_CHAT_SWITCH,
    PLAY_BULLET_CHAT,
    STOP_BULLET_CHAT,
    /****************************************  任务  ****************************************/
    TASK_CHANGE,
    TASK_SCORE_REWARD_CHANGE,
    TASK_ADD,
    ON_TASK_INIT,//任务视图
    ///////////////////////////// vip
    ON_VIP_PRIVATE_DATA,
    /****************************************  活动  ****************************************/
    UPDATE_ACTIVE_DATA,
    ACTIVE_CLOSE,
    NEW_ACTIVE,
    ACTIVE_INIT,

    /****************************************  新手宝典  ****************************************/
    ON_NOVICE_CONFIG,//配置下发
    ON_NOVICE_PRIVATEDATA,//私有数据下发
    ON_UPDATE_NOVICE,//更新私有数据
    ON_NOVICE_OVER,//新手宝典结束
    ACROSS_DAY,//跨天

    UPDATE_APK_PROGRESS,//更新apk进度

    ///////////////////////////////////////////////////////// pvp
    PVP_UNSELECT_TARFER,
    PVP_SELECT_TARFER,
    PVP_SET_TROOPS,
    NETWORK_GAME_START,
    PVP_GAME_CLIENT_START,
    PVP_WAIT_JOIN,
    PVP_READY_LOADING,
    PVP_LOADING_VIEW_SHOW_READY,
    NETWORK_ON_CREATE_TOWER,
    PVP_ON_CREATE_MONSTER,
    PVP_ON_CREATE_MONSTER_OTHER,
    PVP_ON_RUN_AWARY_SYNC,
    PVP_ON_SKILL_HIT,
    PVP_ON_SKILL_SPURTING,
    PVP_ON_SKILL_SPURTING_TARGET,
    PVP_MONSTER_DIE,
    PVP_REMOVE_SCENE_OBJ,
    PVP_CHAT,
    PVP_UPDATE_PROGRESS,
    PVP_CREATE_BO_END,
    PVP_START_BO,
    PVP_NIU_YOU_GUO,
    PVP_EAT_TOWER,
    PVP_REMOVE,
    PVP_VS_TIME_END,
    PVP_DO_MONSTER_MANY_SKILL,
    PVP_DO_MONSTER_SKILL,
    PVP_MONSTER_RELEASE_SKILL,
    PVP_RANK_PRIVATE_INIT,
    PVP_MONSTER_SHOW_OR_HIDE,
    PVP_RANKING_CONFIG,
    PVP_REPLAY_END,
    PVP_CONFIG_INIT,
    

    TRY_UPGRADE_TOWER,
    TRY_REMOVE_TOWER,

    /////////////////////////////
    COOPERATE_INVITE_STATE,
    COOPERATE_WAIT_JOIN,
    COOPERATE_CONFIG_INIT,
    COOPERATE_SET_TROOPS,
    COOPERATE_READY_LOADING,
    COOPERATE_ON_CREATE_MONSTER,
    COOPERATE_CREATE_BO_END,
    COOPERATE_RESTART_LAYER,
    COOPERATE_NEXT_LAYER,
    COOPERATE_PRIVATE_INIT,

    COOPERATE_SHOP_REFRESH,
    COOPERATE_SHOP_BUY_RET,
    COOPERATE_BUY_COUNT,
    COOPERATE_OUT_MATCH,
    COOPERATE_UP_RANKING,
    COOPERATE_FINISH_BUFF,
    ///////////////////////////////////////////////
    CHALLENGE_RANK_UPDATE,
    CHALLENGE_INIT,
    CHALLENGE_REFRESH,
    PLAYER_NAME_CHANGE,

    /************************** 物品 *****************************/
    UP_DROPBOX_DATA,


    /////////////////////////////////////////////赏金
    BOUNTY_CONFIG_REFRESH,
    BOUNTY_DATA_REFRESH,
    BOUNTY_OPEN_GRID,
    BOUNTY_SET_TROOPS,
    BOUNTY_REF_MAP_RET,
    BOUNTY_REF_DAYCOUNT,
    BOUNTY_RELEASE_MAGIC_SKILL,
    BOUNTY_REPLACEWAR,
    BOUNTY_REFRESH_POWER,
    BOUNTY_RET_BUY_COUNT,
    BOUNTY_SHOW_FIGHT_TOWER_TIPS,

    BOUNTY_TOWER_SET_TROOPS,
    BOUNTY_TOWER_ADD_PROP,
    BOUNTY_TOWER_GAME_START,
    BOUNTY_TOWER_REWARD_LAYER,
    BOUNTY_TOWER_REFRESH_DATA,
    ////////////////////////////////////// 战场通行证
    ON_BATTLE_PASS_PRIVATE_DATA,
    ///////////////////////////////////
    CHAT_NEW_MSG,
    CHAT_REFRESH_NEW_MSG_COUNT,
    ///////////////////////////////////
    PVP_SHOP_REFRESH,
    PVP_SHOP_BUY_RET,
    SHOW_CAT_INFO,
    HIDE_CAT_INFO,
    ON_SELECT_CAT_BAB,

    CK_ROLE_INFO_CHANGE,
    CK_BI_REPORT,
    CK_BI_REPORT_EVENT,
    CK_BREAK_POINT,

    ON_CATHOUSE_INFO,

    ON_LUCK_INFO,
    ON_LUCK_PRIVATE,
    ON_LUCK_JION_RET,
    ON_LUCK_JION_CLEAR,

    REFRESH_SYSTEM_OPEN_WAR,

    //////////////////////////////////////////////////////////////////LD
    TRY_CALL_TOWER,
    TRY_STRENGTHEN,
    START_DRAG_TOWER,
    END_DRAG_TOWER,
    CALC_END_DRAG_TOWER,
    CONFLATE_TOWER,
    CREATE_HERO_TABLE,
    HERO_POS_INIT,
    LD_COIN_CHANGE,
    LD_MAP_HP_CHANGE,
    LD_RED_MAP_HP_CHANGE,
    CALL_HERO_SUCCESS,
    CREATE_HERO_TABLE_END,
    TOUCH_EMPTY_POS,
    LD_ACTIVE_STRENGTH_SKILL,
    LD_ACTIVE_MAX_STRENGTH_SKILL,
    LD_STRENGTH_SKILL_CHANGE,
    LD_TRY_STRENGTH_SKILL,
    LD_CONFLATE_WEIGHT_CHANGE,
    LD_REFRESH_MAX_LEVEL,
    CREATURE_STATE_CHANGE,
    REFRESH_HUOJIAN_POS,
    LD_CITY_WALL_HURT,
    NEW_HERO_CREATE,
    // LD_RED_CITY_WALL_HURT,
    LIST_DYNAMIC_END,
    PROPERTY_CHANGE,
    LD_START_GAME,
    LD_TAUNT_BUFF,
    LD_SOMMON_BE_BORN,
    LD_TRY_RELEASE_ANNI_ULTIMATE_SKILL,
    LD_SOMMON_OBJ_DIE,
    LD_CREATURE_DIR_CHANGE,
    LD_MONSTER_DROPS,
    LD_OPEN_DROPS_BOX,
    LD_ADD_SHOOT_TIMES,
    ON_TOWER_TOUCH_START,
    ON_TOWER_TOUCH_MOVE,
    ON_TOWER_TOUCH_END,
    ON_HIT,
    CREATURE_DIE_CHECK,
    ON_CANVAS_RESIZE,
    LD_SPRINIT_CW,

    PLAYER_PROP_CHANGE = 10000,
    MALL_UPDATE_PRIVATE_DATA = 20000,
    SYSTEM_GUIDE_TRIGGER = 50000,
    CP_GUIDE_TRIGGER_EVT = 60000,
    ON_RELATION_RETREWARD = 70000,//更新打赏通知

    ON_RELATION_ADD = 1000000,//更新添加好友
}
